// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj691_NgtQ0plTDI1HXfc7sQ_lo9yqoX8',
    appId: '1:798843270157:web:2d0e737fb3ebad2cc99144',
    messagingSenderId: '798843270157',
    projectId: 'flutter-firebase-3ef5f',
    authDomain: 'flutter-firebase-3ef5f.firebaseapp.com',
    storageBucket: 'flutter-firebase-3ef5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHX7azwWygkijrii3-GSswhqG6sdbnpSU',
    appId: '1:798843270157:android:c58526a25bddb647c99144',
    messagingSenderId: '798843270157',
    projectId: 'flutter-firebase-3ef5f',
    storageBucket: 'flutter-firebase-3ef5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquyDNvxxtJaCdBPAH_2-scC1jORaoZj8',
    appId: '1:798843270157:ios:26ba790490e75ce6c99144',
    messagingSenderId: '798843270157',
    projectId: 'flutter-firebase-3ef5f',
    storageBucket: 'flutter-firebase-3ef5f.firebasestorage.app',
    iosBundleId: 'com.example.reusemartMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCquyDNvxxtJaCdBPAH_2-scC1jORaoZj8',
    appId: '1:798843270157:ios:26ba790490e75ce6c99144',
    messagingSenderId: '798843270157',
    projectId: 'flutter-firebase-3ef5f',
    storageBucket: 'flutter-firebase-3ef5f.firebasestorage.app',
    iosBundleId: 'com.example.reusemartMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj691_NgtQ0plTDI1HXfc7sQ_lo9yqoX8',
    appId: '1:798843270157:web:62dec73d84a52c04c99144',
    messagingSenderId: '798843270157',
    projectId: 'flutter-firebase-3ef5f',
    authDomain: 'flutter-firebase-3ef5f.firebaseapp.com',
    storageBucket: 'flutter-firebase-3ef5f.firebasestorage.app',
  );
}
